export const Environment = {
  DB_PROCUREMENT: 'DB_PROCUREMENT',
  MASTER_DB_HOST: 'MASTER_DB_HOST',
  MASTER_DB_PORT: 'MASTER_DB_PORT',
  MASTER_DB_USER: 'MASTER_DB_USER',
  MASTER_DB_PASS: 'MASTER_DB_PASS',
  SLAVE_DB_HOST: 'SLAVE_DB_HOST',
  SLAVE_DB_PORT: 'SLAVE_DB_PORT',
  SLAVE_DB_USER: 'SLAVE_DB_USER',
  SLAVE_DB_PASS: 'SLAVE_DB_PASS',
} as const;
