/* SELECT PD.PROJECT_NAME,
	PD.LOCATION,
	PD.SUBJECT,
	PD.WORK_DESCRIPTION,
	PD.QUANTITY,
	PD.OUTPUT_PER_DAY,
	BD.STATUS,
	BT.NAME,
	GL.NAME,
	MC.SPECIFICATION_ID,
	MC.QUANTITY,
	MC.UNIT_COST,
	LC.SPECIFICATION_ID,
	LC.NUMBER_OF_PERSON,
	LC.NUMBER_OF_DAYS,
	LC.UNIT_COST,
	EC.EQUIPMENT_DESCRIPTION,
	EC.NUMBER_OF_UNIT,
	EC.number_of_days,
	EC.UNIT_COST
FROM PROJECT_DETAILS AS PD
INNER JOIN BUDGET_DETAILS AS BD ON BD.BUDGET_DETAILS_ID = PD.BUDGET_DETAILS_ID_FK
INNER JOIN BUDGET_TYPES AS BT ON BT.BUDGET_TYPE_ID = BD.BUDGET_TYPE_ID_FK
INNER JOIN GENERAL_LEDGER_ACCOUNTS AS GL ON GL.GENERAL_LEDGER_ACCOUNT_ID = BD.GENERAL_LEDGER_ACCOUNT_ID_FK
INNER JOIN MATERIAL_COSTS AS MC ON MC.PROJECT_DETAILS_ID_FK = PD.PROJECT_DETAILS_ID
INNER JOIN LABOR_COSTS AS LC ON LC.PROJECT_DETAILS_ID_FK = PD.PROJECT_DETAILS_ID
INNER JOIN EQUIPMENT_COSTS AS EC ON EC.PROJECT_DETAIL_ID_FK = PD.PROJECT_DETAILS_ID */
