export enum UnitTypesPatterns {
  CREATE = 'ULZDFINFII',
  FIND_ALL = 'CCN80SXJU7',
  FIND_BY_ID = 'GUOUMIHP9R',
  UPDATE = '1CIXJ4FI26',
  DELETE = '94BVOYWYF3',
}

export enum UnitsOfMeasurePatterns {
  CREATE = 'KCZS6PBIJQ',
  FIND_ALL = 'Q6DE3F7BKE',
  FIND_BY_ID = 'I9FHJ4LUXF',
  UPDATE = 'MLGLELLCDC',
  DELETE = 'VCJ1FVV90C',
}
