name: Deploy

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
  push:
    branches: ['main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Pulling latest codebase from repository
        run: |
          pwd
          git checkout main
          git pull origin main

      - name: Removing previous dist directory
        working-directory: /home/ictd2022/actions-runner/_work/api/api/
        run: |
          rm -rf dist

      - name: Building projects
        run: |
          npx nx build items
          npx nx build procurement
          npx nx build warehouse

      - name: PM2 deployment
        working-directory: /home/ictd2022/actions-runner/_work/api
        run: |
          pm2 delete procurement
          pm2 delete items
          pm2 delete warehouse
          pm2 start ecosystem.config.js
