name: CD
on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        run: |
          pwd
        ## echo "checkout to local main branch"
        # git checkout main
        # echo "pulling the latest code from remote repository"
        # git pull origin main
        # echo "got the latest code now"
