name: CD
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "checkout to local main branch"
          git checkout main
          echo "pulling latest code from remote repository"
          git pull origin main
          echo "got the latest code now"
        working-directory: /home/runner/work/api/api
