name: CD
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        run: |
          pwd
          echo "checkout to local main branch"
          git checkout main
          echo "pulling latest code from remote repository"
          git pull origin main
          echo "got the latest code now"
