name: Production
on:
  push:
    branches:
      - main
jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:${{matrix.language}}'

  sync:
    name: Synching
    runs-on: self-hosted
    needs: analyze
    steps:
      - name: Pulling latest code from remote repository's production branch
        run: |
          git checkout main
          git pull origin main

  building:
    name: Building
    needs: sync
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm i
      - run: npx nx run-many --target=build --parallel=3

  deployment:
    name: Deployment
    needs: building
    runs-on: self-hosted
    steps:
      - name: Deploying application using pm2
        working-directory: /home/ictd2022/actions-runner/_work/api/
        run: |
          pm2 start ecosystem.config.js
          pm2 save
