name: Production
on:
  push:
    branches:
      - main
jobs:
  building:
    name: Building
    runs-on: self-hosted
    strategy:
      matrix:
        node: [18.x]
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
      - name: Setting up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: nrwl/nx-set-shas@v3
      - run: npm i
      - run: npx nx affected --target=build --parallel=3
      - name: Reload pm2 configuration
        run: |
          cd ..
          pwd
          pm2 reload ecosystem.config.js
