name: Production
on:
  push:
    branches:
      - main
jobs:
  building:
    name: Building
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
      - uses: nrwl/nx-set-shas@v3
      - run: npm i
      - run: npx nx run-many --target=build --parallel=3

  deployment:
    name: Deployment
    needs: building
    runs-on: self-hosted
    steps:
      - name: Deploying application using pm2
        working-directory: /home/ictd2022/actions-runner/_work/api/
        run: |
          pm2 start ecosystem.config.js
          pm2 save
