name: Staging
on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: '/language:${{matrix.language}}'

  staging:
    name: Staging
    runs-on: self-hosted
    needs: analyze
    strategy:
      matrix:
        node: [18.x]
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: Setting up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Comparing Base and Head positions
        uses: nrwl/nx-set-shas@v3

      - name: Perform format check
        run: npx nx format:check

      - name: Perform code linting
        run: npx nx affected --target=lint --parallel=3

      - name: Perform code testing
        run: npx nx affected --target=test --parallel=3 --configuration=ci
