name: Staging
on:
  pull_request:
    branches:
      - main

jobs:
  node:
    name: Seeting up Node
    runs-on: self-hosted
    strategy:
      matrix:
        node: [18.x]
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
      - name: Node environment setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

  format:
    name: Perform format checking
    runs-on: self-hosted
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: Comparing Base and Head positions
        uses: nrwl/nx-set-shas@v3

      - run: npx nx format:check

  linting:
    name: Execute code linter
    runs-on: self-hosted
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: Comparing Base and Head positions
        uses: nrwl/nx-set-shas@v3

      - run: npx nx affected --target=lint --parallel=3

  testing:
    name: Execute code tests
    runs-on: self-hosted
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false

      - name: Comparing Base and Head positions
        uses: nrwl/nx-set-shas@v3

      - run: npx nx affected --target=test --parallel=3 --configuration=ci

  # staging:
  #   name: Staging
  #   runs-on: self-hosted
  #   needs: analyze
  #   strategy:
  #     matrix:
  #       node: [18.x]
  #   permissions:
  #     contents: 'read'
  #     actions: 'read'
  #   steps:
  #     - name: Checking out repository
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         clean: false

  #     - name: Setting up node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}

  #     - name: Comparing Base and Head positions
  #       uses: nrwl/nx-set-shas@v3

  #     - name: Perform format check
  #       run: npx nx format:check

  #     - name: Perform code linting
  #       run: npx nx affected --target=lint --parallel=3

  #     - name: Perform code testing
  #       run: npx nx affected --target=test --parallel=3 --configuration=ci
