name: Staging
on:
  pull_request:
    branches:
      - main

jobs:
  staging:
    name: Staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --configuration=ci
      - run: npx nx affected --target=build --parallel=3
  reload:
    name: Reload pm2
    needs: staging
    runs-on: self-hosted
    steps:
      - name: Deploying application using pm2
        working-directory: /home/ictd2022/actions-runner/_work/api/
        run: |
          pm2 reload ecosystem.config.js
