# name: Staging
# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   node:
#     name: Seeting up Node
#     runs-on: self-hosted
#     strategy:
#       matrix:
#         node: [18.x]
#     permissions:
#       contents: 'read'
#       actions: 'read'
#     steps:
#       - name: Checking out repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           clean: false
#       - name: Node environment setup
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node }}

#   formatting:
#     name: Perform format checking
#     runs-on: self-hosted
#     steps:
#       - name: Checking out repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           clean: false

#       - name: Install dependencies
#         run: npm install

#       - name: Comparing Base and Head positions
#         uses: nrwl/nx-set-shas@v3

#       - run: npx nx format:check

#   linting:
#     name: Execute code linter
#     runs-on: self-hosted
#     steps:
#       - name: Checking out repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           clean: false

#       - name: Install dependencies
#         run: npm install

#       - name: Comparing Base and Head positions
#         uses: nrwl/nx-set-shas@v3

#       - run: npx nx affected --target=lint --parallel=3

#   testing:
#     name: Execute code tests
#     runs-on: self-hosted
#     steps:
#       - name: Checking out repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
#           clean: false

#       - name: Install dependencies
#         run: npm install

#       - name: Comparing Base and Head positions
#         uses: nrwl/nx-set-shas@v3

#       - run: npx nx affected --target=test --parallel=3 --configuration=ci
